### PR TITLE
Pdata json api

### PR DESCRIPTION
**Pull request by michelevantaggi02**
Added a translations file to get weapons, titans and maps names.
Adding more stuff like pilot classes and weapons attachments in the future

### CODE REVIEW

**Comment by michelevantaggi02** [comment]
Ow i also merged the new commits of the original master server, didn't remember that

**Comment by michelevantaggi02** [comment]
@barnabwhy Is there a way to get a player database with some data in it? Otherwise I'm considering to create a script that generates random playerdata to use for testing.

**Comment by barnabwhy** [comment]
> @barnabwhy Is there a way to get a player database with some data in it? Otherwise I'm considering to create a script that generates random playerdata to use for testing.

You should be able to just use some online sqlite editor and chuck bogus data in it

**Comment by barnabwhy** [comment]
Also I'd honestly say we should leave the data as untouched as possible cause firstly the game can understand it if we add stuff relating to this to the game client in some way, and also if some web app for example is interacting with the api it should handle this kind of stuff on its end to add flexibility

**Comment by michelevantaggi02** [comment]
> Also I'd honestly say we should leave the data as untouched as possible cause firstly the game can understand it if we add stuff relating to this to the game client in some way, and also if some web app for example is interacting with the api it should handle this kind of stuff on its end to add flexibility

Yeah, i mean, i wasn't thinking about editing the playerdata itself but i would create some dummy-players in my database and give them some random values to the player data just for testing

**Comment by michelevantaggi02** [comment]
Otherwise i'll ask a couple friends and port-forward my master server, to them, to play some games and get some data

**Comment by barnabwhy** [comment]
Gonna close this since it doesn't really add anything that isn't bloat

**Pull request closed without merging**
